### PR TITLE
v2-0-0

### LINKED ISSUE #1: CLDR data version 33 release
Unicode Consortium released CLDR version 33 today and I have updated ex_cldr, ex_cldr_numbers, ex_cldr_lists, ex_cldr_dates_times,ex_unitsandex_money` to use the new data.

There aren't any new locales but I can see there are changes and additions to some language information. I found this upgrade to have no issues in any of my code so hopefully the same for you.

Just bump your version requirements to {ex_cldr, "~> 1.5.0} and hopefully you're good to go.

### PR DESCRIPTION
**Pull request by Schultzer**
This implements the new structure in `:ex_cldr`
waiting for upstream [#94](https://github.com/kipcole9/cldr/pull/94) to be merged.

Let me know what you think.

closes #1

### CODE REVIEW

**Comment by LostKobrakai** [comment]
Thanks for the work. I hope I find some time this we to go over the changes.

**Comment by jung-hunsoo** [comment]
I just got error while upgrading `ex_cldr` to 2.x due to conflict with `cldr_languages`.

It seems that the `mix/test_backend.ex` lacks of `Language` module.

Any solutions there?

**Comment by LostKobrakai** [comment]
cldr_languages is not yet ready for 2.x. I probably won't be able to have a more in depth look at it until I'll be switching my projects and those depend on the also not yet ready https://github.com/kipcole9/cldr_dates_times. Until then you might want to try using it from @Schultzer's github branch. If you do I'd appreciate some feedback on how it went.

**Comment by jung-hunsoo** [comment]
Thanks. Well, I managed to use `Cldr` solely.

@Schultzer I think the problem is either 1) the module `TestBackend.Cldr.Language` is missing, or 2) `doctest TestBackend.Cldr.Language` is not necessary.

But if the `cldr_language` is intended to provide functions, it doesn't need to be structured as a backend. And there's no other use or test of `TestBackend.Cldr.Language`. So I think `TestBackend.Cldr.Language` module won't be required.

**Comment by Schultzer** [comment]
@jung-hunsoo have you tried to clean out `_build` and recompile?
all tests passes on my machine with cldr 2.2.

/edit
The reason why travis fail is because this pr was before upstream [#94](
https://github.com/kipcole9/cldr/pull/94) was merged so this just need to be rebuild and it should pass.

**Comment by LostKobrakai** [comment]
@Schultzer thanks for doing this PR. I'll close this one though as I've not merged your changes for two reasons: I needed to understand what works differently now and I also did a few things differently like not even having a normal public module with functions anymore. But it was a great help to already see how it could've been solved.

I've pushed my changes as v0.2.0, so this package should now be supporting usage with ex_cldr v2.

**Pull request closed without merging**
